# Generated by Django 4.0.2 on 2022-03-13 08:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_email', models.CharField(blank=True, max_length=255, null=True)),
                ('c_address', models.CharField(blank=True, max_length=255, null=True)),
                ('c_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('c_logo', models.ImageField(blank=True, null=True, upload_to='logo')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
